FROM golang:1.14.7
ENV GOPATH /go

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "zip", "unzip"]
RUN ["apt-get", "install", "-y", "python-pip"]
RUN ["pip", "install", "grpcio-tools==1.31.0", "-i", "https://mirrors.aliyun.com/pypi/simple"]

RUN ["rm", "-rf", "/go/src/github.com/golang/protobuf"]
RUN ["go", "get", "-v", "-d", "-u", "github.com/golang/protobuf/protoc-gen-go"]
RUN ["git", "-C", "/go/src/github.com/golang/protobuf", "checkout", "v1.4.2"]
RUN ["go", "install", "github.com/golang/protobuf/protoc-gen-go"]

RUN ["curl", "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip", "-o", "awscli-bundle.zip"]
RUN ["unzip", "awscli-bundle.zip"]
RUN ["./awscli-bundle/install", "-i", "/usr/local/aws", "-b", "/usr/local/bin/aws"]

RUN ["wget", "-O", "protoc.zip", "https://github.com/protocolbuffers/protobuf/releases/download/v3.12.4/protoc-3.12.4-linux-x86_64.zip"]
RUN ["unzip", "-o", "protoc.zip", "-d", "_tmp_protoc/"]
RUN ["cp", "-r", "_tmp_protoc/include/.", "/usr/local/include"]
RUN ["cp", "-r", "_tmp_protoc/bin/.", "/usr/local/bin"]
RUN ["rm", "-f", "protoc.zip"]
RUN ["rm", "-rf", "_tmp_protoc/"]

RUN ["go", "get", "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"]
RUN ["go", "get", "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"]

RUN ["apt-get", "install", "-y", "openjdk-11-jdk"]

RUN ["git", "clone", "https://github.com/grpc/grpc-java.git"]
#RUN ["echo", "skipCodegen=true", ">>", "./grpc-java/gradle.properties"]
#RUN ["echo", "skipAndroid=true", ">>", "./grpc-java/gradle.properties"]
#WORKDIR "./grpc-java"
#RUN ["./gradlew", "build"]
WORKDIR "./grpc-java/compiler"
RUN ["../gradlew", "java_pluginExecutable", "-PskipAndroid=true"]